name: Backend â€“ Build & Deploy (Production)

on:
  push:
    branches:
      - master
    paths:
    - '**'
    - '.github/workflows/app-risqai-backend-prod-AutoDeployTrigger-5b42ba62-8b2b-45cd-997a-6613cdb8a5e9.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production
    concurrency:
      group: backend-production
      cancel-in-progress: false
    env:
      REGISTRY_LOGIN_SERVER: ${{ vars.REGISTRY_LOGIN_SERVER }}
      IMAGE_NAME:            ${{ vars.IMAGE_NAME }}
      RESOURCE_GROUP:        ${{ vars.RESOURCE_GROUP }}
      CONTAINER_APP_NAME:    ${{ vars.CONTAINER_APP_NAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: risqaiprod.azurecr.io
          registryUsername: ${{ secrets.APPRISQAIBACKENDPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPRISQAIBACKENDPROD_REGISTRY_PASSWORD }}
          containerAppName: app-risqai-backend-prod
          resourceGroup: group-risqai-production
          imageToBuild: risqaiprod.azurecr.io/app-risqai-backend-prod:${{ github.sha }}
          minReplicas: 1
          maxReplicas: 10
          _buildArgumentsKey_: |
            _buildArgumentsValues_


